spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/stock_example
    username: root
    password: 1234

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG # Hibernate? ???? SQL ??? ??? ??
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # ??? ????? ???? ?? ?? ex) binding parameter [1] as [BIGINT] - [42]